name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            TARGET="/home/ubuntu/gemini-frontend"
            
            echo "=== Starting Deployment on EC2 ==="

            
            if [ ! -d "$TARGET/.git" ]; then
              echo "=== Cloning repository ==="
              git clone https://github.com/iameerhamza03/gemini-frontend.git $TARGET
            else
              echo "=== Pulling latest code ==="
              cd "$TARGET"
              git pull origin main
            fi

            cd "$TARGET"

            echo "=== Stopping old container ==="
            docker stop gemini-live || true
            docker rm gemini-live || true

            COMMIT_HASH=$(git rev-parse --short HEAD)
            echo "=== Building Docker image: gemini-live-ui:$COMMIT_HASH ==="
            docker build --no-cache -t gemini-live-ui:$COMMIT_HASH .

            echo "=== Running new container ==="
            docker run -d --name gemini-live -p 3000:3000 gemini-live-ui:$COMMIT_HASH

            echo "=== Deployment completed successfully ==="
