name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2️⃣ Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            TARGET="/home/ubuntu/gemini-frontend"
            cd $TARGET || git clone https://github.com/iameerhamza03/gemini-frontend.git $TARGET
            cd $TARGET
            git reset --hard
            git pull origin main

            # Stop and remove old container
            docker stop gemini-live || true
            docker rm gemini-live || true
            sudo fuser -k 3000/tcp || true
            docker rmi $(docker images -q gemini-live-ui) || true

            # Build Docker image with commit hash
            COMMIT_HASH=$(git rev-parse --short HEAD)
            docker build --no-cache -t gemini-live-ui:$COMMIT_HASH .

            # Run new container
            docker run -d --name gemini-live -p 3000:3000 gemini-live-ui:$COMMIT_HASH
