name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        env:
          TARGET: "/home/ubuntu/gemini-frontend"
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: TARGET
          script:     |
            mkdir -p "$TARGET"
            cd "$TARGET"
            echo "Moving to directory..."
            echo "I am now in $(pwd)"
            git pull origin main
            docker build -t gemini-live-ui:new .
            docker run -d -p 3000:3000 --name gemini-live gemini-live-ui:new
